server:
  port: 8083

spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            exposedHeaders:
              - "Upgrade"
              - "Connection"
              - "Sec-WebSocket-Accept"
              - "Sec-WebSocket-Key"
              - "Sec-WebSocket-Version"
            allowCredentials: true
      discovery:
        locator:
          enabled: true
      routes:
        - id: post-service
          uri: lb://post-service
          predicates:
            - Path=/post/**
          filters:
            - RewritePath=/post/(?<path>.*), /$\{path}
        - id: review-service
          uri: lb://review-service
          predicates:
            - Path=/review/**
          filters:
            - RewritePath=/review/(?<path>.*), /$\{path}
        - id: comment-service
          uri: lb://comment-service
          predicates:
            - Path=/comment/**
          filters:
            - RewritePath=/comment/(?<path>.*), /$\{path}
        - id: notification-websocket
          uri: lb:ws://notification-service
          predicates:
            - Path=/notification-ws/**
          filters:
            - RemoveRequestHeader=Sec-WebSocket-Protocol
            - RemoveRequestHeader=Sec-WebSocket-Extensions
            - StripPrefix=1

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/
