name: newsarticleprogram
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5673:5672"
      - "15673:15672"
    networks:
      - microservice-network
  postservice_db:
    container_name: postservice_db
    image: mariadb:latest
    ports:
      - "3316:3306"
    environment:
      MYSQL_ROOT_PASSWORD: pxl
      MYSQL_DATABASE: postservice_db
    networks:
      - microservice-network
  reviewservice_db:
    container_name: reviewservice_db
    image: mariadb:latest
    ports:
      - "3317:3306"
    environment:
      MYSQL_ROOT_PASSWORD: pxl
      MYSQL_DATABASE: reviewservice_db
    networks:
      - microservice-network
  commentservice_db:
    container_name: commentservice_db
    image: mariadb:latest
    ports:
      - "3318:3306"
    environment:
      MYSQL_ROOT_PASSWORD: pxl
      MYSQL_DATABASE: commentservice_db
    networks:
      - microservice-network


networks:
  microservice-network:
    driver: bridge